# KHUDA 9기 ML세션
2026.02.12 (목)

In [101]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, roc_auc_score

In [102]:
# dataset repository path
url = "https://raw.githubusercontent.com/gaeng02/KHUDA-9th-ML/main/week4/dataset.csv"

In [103]:
df = pd.read_csv(url)
df.head()

,id,x1,x2,x3,x4,x5,x6,x7,x8,target
0,1,2.201695,1.213213,4.339964,0.772022,0.431892,0.642472,2.948533,3.176595,0
1,2,-0.768291,-1.130826,0.081463,1.203113,-1.768695,-3.299067,3.254823,-0.860635,1
2,3,1.628744,0.859592,0.157007,0.291862,-2.111989,0.686316,-0.739240,2.628559,0
3,4,-0.327470,2.340356,-3.103323,0.023139,-1.329344,0.546002,-2.149448,0.692142,1
4,5,4.664837,0.691947,2.860601,0.265886,-2.120915,-2.477834,1.302870,3.707435,0

In [104]:
### answer init
answer = [0] * 5

In [105]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      320 non-null    int64
 1   x1      320 non-null    float64
 2   x2      320 non-null    float64
 3   x3      320 non-null    float64
 4   x4      320 non-null    float64
 5   x5      320 non-null    float64
 6   x6      320 non-null    float64
 7   x7      320 non-null    float64
 8   x8      320 non-null    float64
 9   target  320 non-null    int64
dtypes: float64(8), int64(2)
memory usage: 25.1 KB

,id,x1,x2,x3,x4,x5,x6,x7,x8,target
count,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000
mean,160.500000,0.806944,0.943616,0.367748,-0.018247,-0.874966,0.105181,0.323081,1.478618,0.293750
std,92.520268,1.391858,1.376131,2.739319,1.015577,1.557777,1.840643,1.601090,1.741229,0.456192
min,1.000000,-4.131593,-3.912791,-6.273428,-2.419745,-5.147285,-3.914202,-3.340882,-2.999492,0.000000
25%,80.750000,-0.086473,0.122269,-1.273078,-0.708609,-1.968179,-1.217517,-1.017415,0.027702,0.000000
50%,160.500000,0.870092,1.054772,0.609360,-0.016015,-1.016442,0.058887,0.238723,1.626440,0.000000
75%,240.250000,1.710222,1.879487,2.090180,0.668811,0.149204,1.425715,1.474919,2.942616,1.000000
max,320.000000,4.705750,4.906175,8.617379,2.730867,3.977919,4.592126,4.614840,5.784588,1.000000

## Task 0. 초기 설정
다음 설정에 맞게 모델을 만드세요. <br>
별도의 정답은 없지만, 완료되지 않은 경우 Task 수행 불가 <br>
`X_train, y_train`을 이용하여 학습까지 진행하세요.

- feature(X) : `x1~x8`
- target(y) : `target`
- split : `test_size = 0.2, random_state = 212, stratify = y`
- model : `LogisticRegression(max_iter =2000, solver = "lbfgs")`

<br>

이때, X는 `StandardScaler`를 이용하여 데이터 전처리를 진행해주세요.

In [106]:
### Step 1. feature, target Setting
feature_cols = [f"x{i}" for i in range (1, 9)]
X = df[feature_cols]
y = df['target']

### Step 2. Data Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=212, stratify = y)


### Step 3. Data Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


### Step 4. Modeling
lr_clf = LogisticRegression(max_iter=2000, solver="lbfgs")
lr_clf.fit(X_train_scaled, y_train)
lr_pred = lr_clf.predict(X_test_scaled)

In [107]:
scaler.fit(df)
scaled = scaler.transform(df)

## Task 1
test dataset(`X_test`)을 이용하여 Accuracy를 구하세요.  
이때 Accuracy를 `answer[1]` 저장하세요.

In [108]:
## Input Box

accuracy = 0.0

accuracy = accuracy_score(y_test, lr_pred)


answer[1] = accuracy
print(answer[1])

0.890625

## Task 2
`threshold = 0.5`로 Label을 만드세요.  
그리고 `confusion_matrix`을 이용해 TP(True Positive) 개수를 구하세요.  
이때, TP 개수를 answer[2]에 저장하세요.

In [109]:
## Input Box

tp = confusion_matrix(y_test, lr_pred)[1][1]



answer[2] = tp
print(answer[2])

12

## Task 3
이번에는 `threshold = 0.6`으로 F1 Score를 구하세요. <br>
이때, f1 score를 `answer[3]`에 저장하세요.

In [110]:
## Input Box

from sklearn.preprocessing import Binarizer

f1 = 0.0
threshold = 0.6

lr_pred = lr_clf.predict_proba(X_test_scaled)

pred_proba_f1 = lr_pred[:, 1].reshape(-1,1)
binarizer = Binarizer(threshold = threshold).fit(pred_proba_f1)

custom_predict = binarizer.transform(pred_proba_f1)

f1 = f1_score(y_test, custom_predict)

answer[3] = f1
print(answer[3])

0.6896551724137931

## Task 4
threshold를 0.05~0.95까지 0.01 간격으로 바꿔가며 최대가 되는 threshold를 찾으세요. <br>
best_threshold를 answer[5]에 저장하세요. <br>
(만약, F1 score가 동일하다면, 작은 threshold를 선택) <br>

In [111]:
## Input Box

best_threshold = 0.0
best_f1 = 0.0

for threshold in np.arange(0.05, 0.96, 0.01) :




answer[4] = round(best_threshold, 3)
print(answer[4])

IndentationError: expected an indented block after 'for' statement on line 6 (ipython-input-3490807035.py, line 11)

# 정답 확인!

In [112]:
print("=== 작성하신 정답 ===")
for i in range (1, 5) : print("Task " + str(i) + " :: " + str(answer[i]))

=== 작성하신 정답 ===
Task 1 :: 0.890625
Task 2 :: 12
Task 3 :: 0.6896551724137931
Task 4 :: 0

In [113]:
### 정답 채점 코드
import hashlib

ANSWER_URL = "https://raw.githubusercontent.com/gaeng02/KHUDA-9th-ML/main/week4/answer.csv"

def md5 (s) : return hashlib.md5(s.encode("utf-8")).hexdigest()

ans_df = pd.read_csv(ANSWER_URL)
gt = {int(r["task"]): str(r["answer"]).strip().lower()
      for _, r in ans_df.iterrows()}

wrong = []

for i in range(1, 5) :
    user_answer = "" if answer[i] is None else md5(str(answer[i]).strip().lower())
    if (user_answer != gt.get(i, "")) : wrong.append(i)

print("탈출!" if not wrong else f"틀린번호 : {wrong}")

틀린번호 : [4]